[2.0.18] - Updated arg parsing

diff --git a/bin/yayfzf b/bin/yayfzf
--- a/bin/yayfzf
+++ b/bin/yayfzf
@@ -702,33 +702,74 @@ show_example_config() {
 #######################################
 # Command line argument parsing
 #######################################
-SEARCH_QUERY=""
-CONFIG_INIT=false
-if [[ -n "${VERBOSE}" && "${VERBOSE}" != false ]]; then
-  export VERBOSE
-fi
+parse_args() {
+  SEARCH_QUERY=""
+  CONFIG_INIT=false
 
-while [[ $# -gt 0 ]]; do
-  case "${1}" in
-    -t|--them*)       THEME="${2}";                               shift 2 ;;
-    -l|--list-themes) show_themes;                                exit 0  ;;
-    -k|--key*)        show_keybindings;                           exit 0  ;;
-    -i|--init-c*)     CONFIG_INIT=true;                           shift   ;;
-    -s|--show-c*)     show_example_config;                        exit 0  ;;
-    -v|--verb*)       export VERBOSE=true;                        shift   ;;
-    -h)               show_help;                                  exit 0  ;;
-    --help)           show_help_full;                             exit 0  ;;
-    --help-man)       show_help_man;                              exit 0  ;;
-    -V|--vers*)       show_version;                               exit 0  ;;
-    -*)               die "Unknown option: '${1}'. See help for options"  ;;
-    *)                SEARCH_QUERY+="${SEARCH_QUERY:+ }${1}";     shift   ;;
-  esac
-done
+  while [[ $# -gt 0 ]]; do
+    case "${1}" in
+      -t|--theme)
+        [[ -n "${2:-}" ]] || die "Missing value for ${1}"
+        THEME="${2}"
+        shift 2
+        ;;
+      -l|--list-themes)
+        show_themes
+        exit 0
+        ;;
+      -k|--keybindings)
+        show_keybindings
+        exit 0
+        ;;
+      -i|--init-config)
+        CONFIG_INIT=true
+        shift
+        ;;
+      -s|--show-config)
+        show_example_config
+        exit 0
+        ;;
+      -v|--verbose)
+        export VERBOSE=true
+        shift
+        ;;
+      -h)
+        show_help
+        exit 0
+        ;;
+      --help)
+        show_help_full
+        exit 0
+        ;;
+      --help-man)
+        show_help_man
+        exit 0
+        ;;
+      -V|--version)
+        show_version
+        exit 0
+        ;;
+      --)
+        shift
+        SEARCH_QUERY+="${SEARCH_QUERY:+ }${*}"
+        break
+        ;;
+      -*)
+        die "Unknown option: '${1}'. See help for options"
+        ;;
+      *)
+        SEARCH_QUERY+="${SEARCH_QUERY:+ }${1}"
+        shift
+        ;;
+    esac
+  done
+}
 
 #######################################
 # Init
 #######################################
 load_config
+parse_args "${@}"
 resolve_theme
 require_cmd yay fzf
 
